/*
 * Copyright (C) 2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export {PJTabBar, PJTabBarController} from "./src/main/ets/components/PJTabBar"
export {PJTabComponent, PJTabComponentController} from "./src/main/ets/components/PJTabComponent"
export {PJTabBarItemInterface, PJTabBarItem, PJReferenceTabBarItemInterface} from "./src/main/ets/models/PJTabBarItem"
export {PJTabBarItemAttribute} from "./src/main/ets/models/PJTabBarItemAttribute"
export {PJTabBarOptionsInterface, PJTabBarOptions, PJIndicatorPosition, PJIndicatorAnimationType, PJItemEqualDistributionType} from "./src/main/ets/models/PJTabBarOptions"
export {PJBuilder, PJCustomerBuilderInterface} from "./src/main/ets/models/PJBuilder"

