export {
  XTHUDCallback,
  XTHUDBaseOptions,
  XTHUDReactiveBaseOptions,
  XTHUDReactiveOptions,
  XTHUDToastOptions,
  XTHUDLoadingOptions,
  XTHUDProgressOptions,
  XTHUDCustomOptions
} from './src/main/ets/components/XTHUDInterface'

/**
 * @deprecated since 12
 * @useinstead XTPromptHUD
 */
export {
  XTHUDToast,
  XTHUDLoading,
  XTHUDProgress
} from './src/main/ets/components/Deprecated_XTHUD'

/**
 * @deprecated since 12
 * @useinstead XTPromptHUD
 */
export {
  XTHUDManager
} from './src/main/ets/components/Deprecated_XTHUDManager'

/**
 * @deprecated since 12
 * @useinstead XTPromptHUD
 */
export {
  XTEasyHUD
} from './src/main/ets/components/Deprecated_XTEasyHUD'

export {
  XTPromptHUD
} from './src/main/ets/components/XTPromptHUD'